version: '3.8'

services:
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
    
    gateway-server:
        build:
            context: ./gateway-server
            dockerfile: Dockerfile
        container_name: gateway-server
        ports:
            - "3000:3000"
        volumes:
            - ./gateway-server/src:/app/src
        depends_on:
            - redis
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379

volumes:
    redis_data: